In [1]:
import pandas as pd

In [2]:
row = pd.read_csv("C:/Users/rawat/Downloads/movie_dataset.txt")

In [3]:
row.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [4]:
row.shape

(4803, 24)

In [5]:
combined_feature = row['genres'] + row['cast'] + row['keywords'] + row['director']

In [6]:
data = pd.DataFrame(combined_feature)

In [18]:
 data.columns = ['combined_feature']

In [19]:
data.head()

                                    combined_feature
0  Action Adventure Fantasy Science FictionSam Wo...
1  Adventure Fantasy ActionJohnny Depp Orlando Bl...
2  Action Adventure CrimeDaniel Craig Christoph W...
3  Action Crime Drama ThrillerChristian Bale Mich...
4  Action Adventure Science FictionTaylor Kitsch ...

In [23]:
data['combined_feature'].isnull().sum()

426

In [24]:
data.combined_feature.fillna(" ",inplace = True)

### count vectorizing

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit(data['combined_feature'])

CountVectorizer()

In [90]:
cv.vocabulary_

{'action': 127,
 'adventure': 296,
 'fantasy': 7292,
 'science': 18284,
 'fictionsam': 7720,
 'worthington': 22649,
 'zoe': 22944,
 'saldana': 17979,
 'sigourney': 18797,
 'weaver': 22130,
 'stephen': 19454,
 'lang': 12071,
 'michelle': 13859,
 'rodriguezculture': 17313,
 'clash': 3666,
 'future': 8354,
 'space': 19172,
 'war': 21937,
 'colony': 3847,
 'societyjames': 19061,
 'cameron': 2920,
 'actionjohnny': 165,
 'depp': 5225,
 'orlando': 15332,
 'bloom': 2185,
 'keira': 11513,
 'knightley': 11791,
 'stellan': 19445,
 'skarsg': 18906,
 'u00e5rd': 21151,
 'chow': 3548,
 'yun': 22834,
 'fatocean': 7457,
 'drug': 6279,
 'abuse': 96,
 'exotic': 6989,
 'island': 10790,
 'east': 6537,
 'india': 10597,
 'trading': 20824,
 'company': 4133,
 'love': 12713,
 'of': 15200,
 'one': 15279,
 'lifegore': 12458,
 'verbinski': 21660,
 'crimedaniel': 4547,
 'craig': 4472,
 'christoph': 3585,
 'waltz': 21931,
 'u00e9a': 21171,
 'seydoux': 18513,
 'ralph': 16651,
 'fiennes': 7762,
 'monica': 14134,
 'belluccispy': 1840,
 'based': 1644,
 'on': 15278,
 'novel': 15093,
 'secret': 18370,
 'agent': 444,
 'sequel': 18442,
 'mi6sam': 13843,
 'mendes': 13746,
 'crime': 4518,
 'drama': 5842,
 'thrillerchristian': 20344,
 'bale': 1471,
 'michael': 13850,
 'caine': 2858,
 'gary': 8538,
 'oldman': 15240,
 'anne': 903,
 'hathaway': 9487,
 'tom': 20724,
 'hardydc': 9399,
 'comics': 4117,
 'fighter': 7773,
 'terrorist': 20152,
 'identity': 10477,
 'burglarchristopher': 2741,
 'nolan': 15039,
 'fictiontaylor': 7737,
 'kitsch': 11748,
 'lynn': 12863,
 'collins': 3829,
 'samantha': 18010,
 'morton': 14255,
 'willem': 22402,
 'dafoe': 4839,
 'thomas': 20243,
 'haden': 9235,
 'churchbased': 3605,
 'mars': 13271,
 'medallion': 13675,
 'travel': 20895,
 'princessandrew': 16363,
 'stanton': 19369,
 'adventuretobey': 370,
 'maguire': 13009,
 'kirsten': 11733,
 'dunst': 6364,
 'james': 10898,
 'franco': 8169,
 'church': 3604,
 'topher': 20750,
 'gracedual': 8956,
 'amnesia': 756,
 'sandstorm': 18055,
 'life': 12453,
 'forgivenesssam': 8099,
 'raimi': 16633,
 'animation': 866,
 'familyzachary': 7274,
 'levi': 12385,
 'mandy': 13115,
 'moore': 14175,
 'donna': 5741,
 'murphy': 14434,
 'ron': 17706,
 'perlman': 15807,
 'gaineyhostage': 8403,
 'magic': 12995,
 'horse': 10234,
 'fairy': 7063,
 'tale': 19946,
 'musicalbyron': 14460,
 'howard': 10294,
 'fictionrobert': 7711,
 'downey': 5822,
 'jr': 11238,
 'chris': 3553,
 'hemsworth': 9671,
 'mark': 13237,
 'ruffalo': 17839,
 'evans': 6935,
 'scarlett': 18168,
 'johanssonmarvel': 11125,
 'comic': 4110,
 'superhero': 19723,
 'book': 2295,
 'visionjoss': 21798,
 'whedon': 22288,
 'familydaniel': 7144,
 'radcliffe': 16600,
 'rupert': 17860,
 'grint': 9089,
 'emma': 6753,
 'watson': 22104,
 'felton': 7513,
 'gambonwitch': 8446,
 'broom': 2626,
 'school': 18224,
 'witchcraft': 22521,
 'wizardrydavid': 22544,
 'yates': 22748,
 'fantasyben': 7300,
 'affleck': 395,
 'henry': 9699,
 'cavill': 3237,
 'gal': 8409,
 'gadot': 8388,
 'amy': 766,
 'adams': 224,
 'jesse': 11037,
 'eisenbergdc': 6631,
 'vigilante': 21720,
 'revengezack': 17051,
 'snyder': 19048,
 'fictionbrandon': 7593,
 'routh': 17795,
 'kevin': 11583,
 'spacey': 19185,
 'kate': 11423,
 'bosworth': 2358,
 'marsden': 13276,
 'parker': 15566,
 'poseysaving': 16223,
 'the': 20188,
 'world': 22638,
 'dc': 5040,
 'invulnerability': 10718,
 'superherobryan': 19725,
 'singer': 18856,
 'thriller': 20279,
 'olga': 15245,
 'kurylenko': 11953,
 'mathieu': 13383,
 'amalric': 707,
 'judi': 11252,
 'dench': 5190,
 'giancarlo': 8672,
 'gianninikilling': 8674,
 'undercover': 21453,
 'british': 2579,
 'servicemarc': 18475,
 'forster': 8108,
 'bill': 2010,
 'nighywitch': 14983,
 'fortune': 8119,
 'teller': 20111,
 'bondage': 2269,
 'monstergore': 14154,
 'westernjohnny': 22245,
 'armie': 1061,
 'hammer': 9320,
 'william': 22403,
 'fichtner': 7570,
 'helena': 9641,
 'bonham': 2280,
 'carter': 3132,
 'badge': 1398,
 'daletexas': 4860,
 'survivor': 19782,
 'texas': 20171,
 'ranger': 16694,
 'partnergore': 15601,
 'fictionhenry': 7647,
 'shannon': 18555,
 'costner': 4392,
 'diane': 5338,
 'lanesaving': 12070,
 'superhumanzack': 19734,
 'family': 7097,
 'barnes': 1582,
 'moseley': 14262,
 'anna': 894,
 'popplewell': 16191,
 'skandar': 18905,
 'keynes': 11586,
 'georgie': 8618,
 'henleybased': 9683,
 'fictional': 7579,
 'place': 16024,
 'brother': 2631,
 'sister': 18884,
 'relationship': 16897,
 'lion': 12538,
 'human': 10352,
 'beingandrew': 1812,
 'adamson': 229,
 'fiction': 7575,
 'adventurerobert': 360,
 'johanssonnew': 11126,
 'york': 22796,
 'shield': 18671,
 'marvel': 13314,
 'bookjoss': 2298,
 'fantasyjohnny': 7343,
 'pen': 15750,
 'u00e9lope': 21200,
 'cruz': 4734,
 'ian': 10461,
 'mcshane': 13640,
 'mcnally': 13623,
 'geoffrey': 8615,
 'rushsea': 17867,
 'captain': 3014,
 'mutiny': 14578,
 'sword': 19872,
 'prime': 16352,
 'ministerrob': 13971,
 'marshall': 13282,
 'comedy': 3873,
 'fictionwill': 7747,
 'smith': 18985,
 'tommy': 20733,
 'lee': 12251,
 'jones': 11167,
 'josh': 11215,
 'brolin': 2607,
 'stuhlbarg': 19640,
 'thompsontime': 20264,
 'time': 20666,
 'machine': 12909,
 'alien': 620,
 'government': 8939,
 'agency': 442,
 'seeing': 18391,
 'futurebarry': 8357,
 'sonnenfeld': 19125,
 'fantasymartin': 7356,
 'freeman': 8217,
 'mckellen': 13587,
 'richard': 17111,
 'armitage': 1064,
 'ken': 11542,
 'stott': 19556,
 'graham': 8963,
 'mctavishcorruption': 13648,
 'elves': 6725,
 'dwarves': 6475,
 'orcs': 15315,
 'middle': 13867,
 'earth': 6533,
 'tolkien': 20721,
 'peter': 15847,
 'jackson': 10847,
 'fantasyandrew': 7297,
 'garfield': 8509,
 'stone': 19525,
 'rhys': 17094,
 'ifans': 10499,
 'denis': 5200,
 'leary': 12232,
 'campbell': 2929,
 'scottloss': 18323,
 'father': 7442,
 'serum': 18469,
 'scientific': 18289,
 'experimentmarc': 7001,
 'webb': 22136,
 'adventurerussell': 362,
 'crowe': 4719,
 'cate': 3198,
 'blanchett': 2132,
 'max': 13417,
 'von': 21828,
 'sydow': 19881,
 'hurt': 10400,
 'strongrobin': 19617,
 'hood': 10082,
 'archer': 993,
 'knight': 11788,
 'sherwood': 18663,
 'forest': 8088,
 'bow': 2385,
 'and': 778,
 'arrowridley': 1109,
 'scott': 18310,
 'mctavishelves': 13649,
 'hobbit': 9971,
 'dragonpeter': 5839,
 'fantasydakota': 7314,
 'blue': 2190,
 'richards': 17113,
 'nicole': 14950,
 'kidman': 11625,
 'daniel': 4903,
 'sam': 18008,
 'elliott': 6701,
 'eva': 6928,
 'greenengland': 9030,
 'compass': 4138,
 'experiment': 6996,
 'lordship': 12669,
 'unclechris': 21448,
 'weitz': 22173,
 'actionnaomi': 185,
 'watts': 22107,
 'jack': 10839,
 'black': 2088,
 'adrien': 279,
 'brody': 2600,
 'kretschmann': 11891,
 'colin': 3809,
 'hanksfilm': 9351,
 'business': 2804,
 'screenplay': 18333,
 'show': 18740,
 'film': 7802,
 'making': 13049,
 'producerpeter': 16401,
 'romance': 17353,
 'thrillerkate': 20459,
 'winslet': 22494,
 'leonardo': 12327,
 'dicaprio': 5349,
 'frances': 8158,
 'fisher': 7938,
 'billy': 2018,
 'zane': 22873,
 'kathy': 11434,
 'batesshipwreck': 1674,
 'iceberg': 10468,
 'ship': 18691,
 'panic': 15502,
 'titanicjames': 20694,
 'fictionchris': 7607,
 'robert': 17254,
 'johansson': 11122,
 'sebastian': 18363,
 'stan': 19357,
 'anthony': 929,
 'mackiecivil': 12925,
 'superheroanthony': 19724,
 'russo': 17884,
 'alexander': 592,
 'rihanna': 17172,
 'brooklyn': 2620,
 'decker': 5112,
 'tadanobu': 19913,
 'asanofight': 1143,
 'navy': 14802,
 'mind': 13950,
 'reading': 16770,
 'hong': 10075,
 'kong': 11826,
 'soccerpeter': 19053,
 'berg': 1890,
 'thrillerchris': 20343,
 'pratt': 16284,
 'bryce': 2681,
 'dallas': 4862,
 'irrfan': 10761,
 'khan': 11597,
 'vincent': 21748,
 'onofrio': 15282,
 'nick': 14940,
 'robinsonmonster': 17272,
 'dna': 5598,
 'tyrannosaurus': 21073,
 'rex': 17063,
 'velociraptor': 21643,
 'islandcolin': 10792,
 'trevorrow': 20934,
 'thrillerdaniel': 20362,
 'javier': 10957,
 'bardem': 1562,
 'naomie': 14751,
 'harrisspy': 9448,
 'sociopath': 19063,
 'killer': 11657,
 'art': 1115,
 'gallerysam': 8425,
 'fantasytobey': 7385,
 'alfred': 608,
 'molina': 14113,
 'rosemary': 17746,
 'harrisdual': 9436,
 'pizza': 16020,
 'boy': 2403,
 'sequelsam': 18449,
 'gwyneth': 9206,
 'paltrow': 15484,
 'don': 5727,
 'cheadle': 3414,
 'guy': 9198,
 'pearce': 15703,
 'rebecca': 16787,
 'hallterrorist': 9300,
 'terror': 20148,
 'tennessee': 20127,
 'malibu': 13066,
 'comicshane': 4118,
 'adventuremia': 353,
 'wasikowska': 22082,
 'johnny': 11131,
 'crispin': 4675,
 'gloverbased': 8804,
 'queen': 16556,
 'alice': 616,
 'in': 10580,
 'wonderlandtim': 22580,
 'burton': 2782,
 'thrillerhugh': 20419,
 'jackman': 10843,
 'halle': 9286,
 'berry': 1927,
 'patrick': 15660,
 'stewart': 19487,
 'famke': 7277,
 'janssenmutant': 10936,
 'superhuman': 19732,
 'beastbrett': 1744,
 'ratner': 16739,
 'familybilly': 7119,
 'crystal': 4742,
 'john': 11128,
 'goodman': 8885,
 'steve': 19475,
 'buscemi': 2786,
 'helen': 9640,
 'mirren': 13996,
 'noah': 15030,
 'johnstonmonster': 11149,
 'dormitory': 5781,
 'games': 8452,
 'best': 1936,
 'frienddan': 8251,
 'scanlon': 18162,
 'adventureshia': 367,
 'labeouf': 11988,
 'megan': 13693,
 'fox': 8130,
 'duhamel': 6321,
 'rainn': 16644,
 'wilson': 22437,
 'tyrese': 21074,
 'gibsonegypt': 8688,
 'sun': 19708,
 'chaos': 3355,
 'symbol': 19889,
 'artifactmichael': 1125,
 'bay': 1706,
 'adventuremark': 350,
 'wahlberg': 21863,
 'stanley': 19367,
 'tucci': 21009,
 'kelsey': 11533,
 'grammer': 8976,
 'nicola': 14947,
 'peltz': 15749,
 'reynorsequel': 17076,
 'transformers': 20863,
 'giant': 8675,
 'robot': 17275,
 'robotmichael': 17280,
 'familyjames': 7177,
 'mila': 13890,
 'kunis': 11945,
 'rachel': 16591,
 'weisz': 22170,
 'williams': 22404,
 'zach': 22855,
 'braffcircus': 2439,
 'witch': 22520,
 'hope': 10094,
 'illusionsam': 10538,
 'jamie': 10910,
 'foxx': 8140,
 'dane': 4896,
 'dehaan': 5133,
 'scottobsession': 18326,
 'electrocutionmarc': 6663,
 'fictiongarrett': 7638,
 'hedlund': 9608,
 'jeff': 10984,
 'bridges': 2549,
 'olivia': 15251,
 'wilde': 22372,
 'bruce': 2659,
 'boxleitner': 2402,
 'yaya': 22750,
 'dacostaartificial': 4836,
 'intelligence': 10659,
 'computer': 4148,
 'program': 16412,
 'dystopia': 6498,
 'computerjoseph': 4150,
 'kosinski': 11851,
 'comedyowen': 4043,
 'larry': 12108,
 'cable': 2846,
 'emily': 6750,
 'mortimer': 14252,
 'turturrocar': 21047,
 'race': 16583,
 'anthropomorphism': 931,
 'friendjohn': 8253,
 'lasseter': 12129,
 'fictionryan': 7719,
 'reynolds': 17067,
 'blake': 2118,
 'lively': 12568,
 'sarsgaard': 18094,
 'tim': 20664,
 'robbins': 17250,
 'strongdc': 19614,
 'transformation': 20860,
 'infectionmartin': 10619,
 'comedytom': 4094,
 'hanks': 9349,
 'allen': 652,
 'ned': 14828,
 'beatty': 1752,
 'joan': 11086,
 'cusack': 4803,
 'keatonhostage': 11480,
 'college': 3817,
 'toy': 20803,
 'barbie': 1556,
 'animationlee': 875,
 'unkrich': 21491,
 'anton': 940,
 'yelchin': 22761,
 'moon': 14172,
 'bloodgood': 2181,
 'howardsaving': 10301,
 'artificial': 1126,
 'prophecy': 16425,
 'san': 18026,
 'francisco': 8162,
 'cyborgmcg': 4822,
 'actionvin': 205,
 'diesel': 5377,
 'paul': 15677,
 'walker': 21891,
 'dwayne': 6476,
 'johnson': 11133,
 'rodriguez': 17312,
 'gibsoncar': 8685,
 'speed': 19217,
 'revenge': 17037,
 'suspense': 19792,
 'carjames': 3058,
 'wan': 21932,
 'horror': 10114,
 'thrillerbrad': 20313,
 'pitt': 16008,
 'mireille': 13989,
 'enos': 6791,
 'abigail': 83,
 'hargrove': 9407,
 'sterling': 19467,
 'jerins': 11024,
 'daledystopia': 4859,
 'apocalypse': 955,
 'zombie': 22947,
 'nuclear': 15118,
 'weapons': 22126,
 'multiple': 14362,
 'perspectivesmarc': 15833,
 'fictionhugh': 7649,
 'mcavoy': 13455,
 'fassbender': 7432,
 'jennifer': 11012,
 'lawrence': 12185,
 'berry1970s': 1928,
 'mutant': 14569,
 'bookbryan': 2296,
 'pine': 15973,
 'zachary': 22857,
 'quinto': 16568,
 'karl': 11395,
 'urban': 21506,
 'simon': 18835,
 'peggspacecraft': 15733,
 'friendship': 8267,
 'futuristic': 8365,
 'spacej': 19176,
 'abrams': 93,
 'fantasynicholas': 7365,
 'hoult': 10271,
 'eleanor': 6656,
 'tomlinson': 20731,
 'ewan': 6968,
 'mcgregor': 13564,
 'mcshanebased': 13642,
 'giantbryan': 8676,
 'romanceleonardo': 17549,
 'tobey': 20702,
 'carey': 3045,
 'mulligan': 14355,
 'joel': 11111,
 'edgerton': 6581,
 'elizabeth': 6686,
 'debickibased': 5095,
 'infidelity': 10621,
 'obsession': 15176,
 '3dbaz': 26,
 'luhrmann': 12808,
 'romancejake': 17491,
 'gyllenhaal': 9210,
 'gemma': 8585,
 'arterton': 1117,
 'ben': 1851,
 'kingsley': 11700,
 'toussaintpersia': 20784,
 'against': 431,
 'armageddon': 1056,
 'regentmike': 16855,
 'newell': 14894,
 'adventureidris': 327,
 'elba': 6646,
 'charlie': 3377,
 'hunnam': 10369,
 'day': 5028,
 'burn': 2758,
 'gormandystopia': 8914,
 'monster': 14152,
 'imaxguillermo': 10548,
 'del': 5141,
 'toro': 20758,
 'malkovich': 13075,
 'jeong': 11018,
 'mcdormand': 13523,
 'duhamelmoon': 6322,
 'spacecraft': 19174,
 'traitor': 20852,
 'bodyguard': 2226,
 'planetmichael': 16043,
 'actionharrison': 152,
 'ford': 8068,
 'shia': 18668,
 'ray': 16756,
 'winstone': 22499,
 'karen': 11385,
 'allensaving': 656,
 'riddle': 17143,
 'whip': 22297,
 'treasure': 20917,
 'mexico': 13832,
 'citysteven': 3644,
 'spielberg': 19235,
 'familyraymond': 7240,
 'ochoa': 15188,
 'bright': 2564,
 'jeffrey': 10989,
 'wright': 22666,
 'maleah': 13063,
 'nipay': 15005,
 'padillatyrannosaurus': 15436,
 'friends': 8259,
 'alternate': 690,
 'history': 9870,
 'dinosaur': 5418,
 'fearpeter': 7481,
 'sohn': 19076,
 'actionkelly': 168,
 'macdonald': 12894,
 'julie': 11268,
 'walters': 21928,
 'connolly': 4201,
 'thompson': 20253,
 'mckiddscotland': 13595,
 'rebel': 16789,
 'bravery': 2479,
 'kingdom': 11691,
 'archerbrenda': 994,
 'chapman': 3362,
 'pegg': 15730,
 'saldanasequel': 17980,
 'stranded': 19566,
 'hatred': 9493,
 'operajustin': 15296,
 'lin': 12499,
 'familyben': 7117,
 'burtt': 2784,
 'elissa': 6684,
 'garlin': 8518,
 'fred': 8206,
 'willard': 22398,
 'ratzenbergerromantic': 16742,
 'comedyandrew': 3884,
 'tucker': 21013,
 'jackie': 10842,
 'chan': 3329,
 'hiroyuki': 9863,
 'sanada': 18028,
 'yvan': 22851,
 'attalambassadorbrett': 1239,
 'fictionjohn': 7663,
 'amanda': 710,
 'peet': 15725,
 'chiwetel': 3523,
 'ejiofor': 6637,
 'thandie': 20183,
 'newton': 14913,
 'oliver': 15250,
 'plattcivilization': 16061,
 'natural': 14790,
 'disaster': 5547,
 'end': 6771,
 'apocalypseroland': 959,
 'emmerich': 6755,
 'dramagary': 5972,
 'jim': 11073,
 'carrey': 3114,
 'valentine': 21549,
 'daryl': 4966,
 'sabara': 17914,
 'sage': 17954,
 'ryanholiday': 17896,
 'victorian': 21698,
 'england': 6783,
 'money': 14129,
 'christmas': 3575,
 'everobert': 6952,
 'zemeckis': 22904,
 'adventuremila': 355,
 'channing': 3349,
 'tatum': 20021,
 'sean': 18354,
 'bean': 1728,
 'eddie': 6576,
 'redmayne': 16826,
 'douglas': 5799,
 'boothjupiter': 2320,
 'woman': 22566,
 'director': 5428,
 '3d': 24,
 'interspecies': 10675,
 'romancelilly': 17550,
 'wachowski': 21845,
 'adventurealexander': 299,
 'margot': 13198,
 'robbie': 17249,
 'samuel': 18021,
 'djimon': 5593,
 'hounsouafrica': 10274,
 'feral': 7525,
 'child': 3475,
 'tarzan': 20010,
 'jungle': 11284,
 'animal': 858,
 'attackdavid': 1235,
 'fantasywilliam': 7390,
 'henley': 9682,
 'liam': 12425,
 'neesonsaving': 14833,
 'self': 18412,
 'sacrificeandrew': 17927,
 'fictionjames': 7653,
 'nicholas': 14933,
 'oscar': 15355,
 'isaacmutant': 10773,
 'supernatural': 19738,
 'powers': 16265,
 'heath': 9585,
 'ledger': 12247,
 'aaron': 57,
 'eckhart': 6565,
 'maggie': 12994,
 'gyllenhaaldc': 9211,
 'scarecrow': 18165,
 'sadismchristopher': 17930,
 'adventureed': 318,
 'asner': 1171,
 'christopher': 3587,
 'plummer': 16096,
 'jordan': 11202,
 'nagai': 14720,
 'bob': 2211,
 'peterson': 15851,
 'delroy': 5164,
 'lindoage': 12512,
 'difference': 5382,
 'central': 3277,
 'south': 19164,
 'america': 738,
 'balloon': 1484,
 'floating': 8001,
 'airpete': 507,
 'docter': 5611,
 'fictionseth': 7723,
 'rogen': 17323,
 'reese': 16839,
 'witherspoon': 22529,
 'hugh': 10337,
 'laurie': 12159,
 'rudd': 17826,
 'kiefer': 11639,
 'sutherlandalien': 19821,
 'duringcreditsstingerconrad': 6395,
 'vernon': 21672,
 'terrence': 20142,
 'shaun': 18587,
 'toub': 20775,
 'paltrowmiddle': 15485,
 'arms': 1068,
 'dealer': 5052,
 'superherojon': 19728,
 'favreau': 7463,
 'sacha': 17921,
 'baron': 1593,
 'cohen': 3787,
 'asa': 1141,
 'butterfield': 2817,
 'chlo': 3524,
 'u00eb': 21238,
 'grace': 8954,
 'moretz': 14204,
 'winstonelibrary': 22500,
 'clock': 3719,
 'key': 11585,
 'toymartin': 20804,
 'scorsese': 18306,
 'westernwill': 22265,
 'kline': 11774,
 'kenneth': 11557,
 'branagh': 2451,
 'salma': 17996,
 'hayek': 9528,
 'emmet': 6759,
 'walshsteampunk': 21920,
 'tv': 21053,
 'series': 18460,
 'steam': 19412,
 'locomotive': 12602,
 'dragbarry': 5833,
 'kinnaman': 11710,
 'viola': 21760,
 'davis': 5006,
 'jared': 10945,
 'letodc': 12369,
 'shared': 18563,
 'universe': 21484,
 'anti': 935,
 'hero': 9734,
 'mission': 14022,
 'villaindavid': 21738,
 'ayer': 1338,
 'familysteve': 7257,
 'carell': 3040,
 'lauren': 12154,
 'jimmy': 11078,
 'bennett': 1865,
 'higginsfather': 9799,
 'son': 19114,
 'daily': 4851,
 'married': 13268,
 'couple': 4416,
 'support': 19754,
 'fathertom': 7454,
 'shadyac': 18526,
 'fictiontom': 7741,
 'cruise': 4730,
 'blunt': 2196,
 'brendan': 2508,
 'gleeson': 8786,
 'paxton': 15690,
 'jonas': 11164,
 'armstrongdeja': 1072,
 'vu': 21843,
 'warp': 22037,
 'restart': 17003,
 'wardoug': 21974,
 'liman': 12496,
 'actionkevin': 169,
 'chaim': 3305,
 'girafi': 8741,
 'rick': 17131,
 'aviles': 1319,
 'call': 2880,
 'zitto': 22937,
 'kazannocean': 11464,
 'tattoo': 20020,
 'water': 22091,
 'dystopiakevin': 6506,
 'fictiondennis': 7618,
 'quaid': 16539,
 'marlon': 13249,
 'wayans': 22113,
 'sienna': 18789,
 'miller': 13920,
 'joseph': 11213,
 'gordon': 8903,
 'levittterrorist': 12393,
 'hostage': 10254,
 'technology': 20065,
 'warheadstephen': 21988,
 'sommers': 19112,
 'familyamy': 7108,
 'poehler': 16104,
 'phyllis': 15913,
 'kind': 11685,
 'hader': 9236,
 'lewis': 12403,
 'blackdream': 2090,
 'cartoon': 3137,
 'imaginary': 10543,
 'friend': 8247,
 'familypete': 7235,
 'fantasyneel': 7364,
 'sethi': 18482,
 'murray': 14436,
 'idris': 10498,
 'johanssonbased': 11123,
 'snake': 19025,
 'wolf': 22552,
 'elephant': 6668,
 'tigerjon': 20650,
 'mickey': 13864,
 'rourkemalibu': 17791,
 'revengejon': 17043,
 'dramakristen': 6061,
 'charlize': 3378,
 'theron': 20212,
 'claflin': 3651,
 'mcshanequeen': 13644,
 'immortality': 10562,
 'forestrupert': 8095,
 'sanders': 18040,
 'romanceangelina': 17372,
 'jolie': 11160,
 'elle': 6696,
 'fanning': 7288,
 'sharlto': 18573,
 'copley': 4303,
 'riley': 17176,
 'juno': 11294,
 'templefairy': 20118,
 'villain': 21737,
 'sleeping': 18959,
 'beauty': 1760,
 'dark': 4944,
 'talerobert': 19948,
 'stromberg': 19609,
 'thrillerandy': 20292,
 'serkis': 18464,
 'jason': 10953,
 'clarke': 3660,
 'keri': 11567,
 'russell': 17874,
 'toby': 20707,
 'kebbellleader': 11487,
 'post': 16229,
 'apocalyptic': 961,
 'forestmatt': 8094,
 ...}

In [27]:
vector = cv.transform(data['combined_feature'])

In [28]:
vector.shape

(4803, 22980)

In [29]:
type(vector)

scipy.sparse.csr.csr_matrix

In [30]:
vector.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### cosine similarity

In [31]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(vector)

In [32]:
cos_sim.shape

(4803, 4803)

In [34]:
data_sim =pd.DataFrame(cos_sim)

In [35]:
data_sim.head()

,0,1,2,3,4,5,6,7,8,9,...,4793,4794,4795,4796,4797,4798,4799,4800,4801,4802
0,1.000000,0.078567,0.091287,0.042563,0.217597,0.087039,0.0,0.117851,0.093659,0.089087,...,0.000000,0.0,0.000000,0.040825,0.0,0.042563,0.0,0.000000,0.0,0.0
1,0.078567,1.000000,0.043033,0.000000,0.041030,0.164122,0.0,0.037037,0.132453,0.041996,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.041030,0.0,0.0
2,0.091287,0.043033,1.000000,0.093250,0.190693,0.047673,0.0,0.215166,0.051299,0.195180,...,0.000000,0.0,0.000000,0.000000,0.0,0.046625,0.0,0.000000,0.0,0.0
3,0.042563,0.000000,0.093250,1.000000,0.044455,0.088911,0.0,0.040129,0.095673,0.091003,...,0.052129,0.0,0.095673,0.083406,0.0,0.130435,0.0,0.044455,0.0,0.0
4,0.217597,0.041030,0.190693,0.044455,1.000000,0.136364,0.0,0.164122,0.048912,0.139573,...,0.000000,0.0,0.000000,0.085280,0.0,0.044455,0.0,0.000000,0.0,0.0

In [43]:
def to_lower(item) :
    return item.lower()
cols = []
cols = data['title'].apply(to_lower)
data_sim.columns = cols

In [44]:
data_sim.head()

title,avatar,pirates of the caribbean: at world's end,spectre,the dark knight rises,john carter,spider-man 3,tangled,avengers: age of ultron,harry potter and the half-blood prince,batman v superman: dawn of justice,...,on the downlow,sanctuary: quite a conundrum,bang,primer,cavite,el mariachi,newlyweds,"signed, sealed, delivered",shanghai calling,my date with drew
0,1.000000,0.078567,0.091287,0.042563,0.217597,0.087039,0.0,0.117851,0.093659,0.089087,...,0.000000,0.0,0.000000,0.040825,0.0,0.042563,0.0,0.000000,0.0,0.0
1,0.078567,1.000000,0.043033,0.000000,0.041030,0.164122,0.0,0.037037,0.132453,0.041996,...,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.041030,0.0,0.0
2,0.091287,0.043033,1.000000,0.093250,0.190693,0.047673,0.0,0.215166,0.051299,0.195180,...,0.000000,0.0,0.000000,0.000000,0.0,0.046625,0.0,0.000000,0.0,0.0
3,0.042563,0.000000,0.093250,1.000000,0.044455,0.088911,0.0,0.040129,0.095673,0.091003,...,0.052129,0.0,0.095673,0.083406,0.0,0.130435,0.0,0.044455,0.0,0.0
4,0.217597,0.041030,0.190693,0.044455,1.000000,0.136364,0.0,0.164122,0.048912,0.139573,...,0.000000,0.0,0.000000,0.085280,0.0,0.044455,0.0,0.000000,0.0,0.0

In [152]:
def predict():
    movie = input("what do you want to see")
    movie= movie.lower()
    ind = data_sim[data_sim[movie] > 0.196][movie].sort_values(ascending = False).index
    print(cols[ind])

In [155]:
predict()

what do you want to seeharry potter and the half-blood prince
8          harry potter and the half-blood prince
114           harry potter and the goblet of fire
113     harry potter and the order of the phoenix
197      harry potter and the philosopher's stone
276       harry potter and the chamber of secrets
191      harry potter and the prisoner of azkaban
1686                                the borrowers
305                               treasure planet
2826                                 time bandits
Name: title, dtype: object